server:
  port: 8006
  servlet:
    context-path: /api

spring:
  application:
    name: InvoicingSystem

  datasource:
    url: jdbc:postgresql://145.223.22.133:5432/invoicing_db
    username: invoicing_db_user
    password: 123!@#123Aa

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  web:
    error:
      whitelabel:
        enabled: false

app:
  default-password: "password@123"
  jwt:
    secret: "9a6747b38864482310183fd3438466b042d33458557e491c6e1e19d9c22e4c44"
    expiration: 86400000
  file:
    storage-path: "/tmk_ws/saico_project_management/uploads"